### ISSUE TITLE
Accessing fields from Response

### ISSUE THREAD

**Issue by timinho** [marlon-be/marlon-ogone#63]
I'm trying to access the fields from the response. Is it correct I have to make sure to add this line?

$shaComposer->addParameterFilter(new ShaOutParameterFilter); //optional

If so, when I do, Im getting Class 'ShaOutParameterFilter'  not found.

use PostFinance\Ecommerce\EcommercePaymentResponse;
use PostFinance\ShaComposer\AllParametersShaComposer;

are present and the rest of the payment flow works like a breeze.

Any guidance on accessing the response fields would be much appreciated or maybe an extra paragraph in the readme?

**Comment by jelte** [comment]
Did you forget?
```php
use Ogone/ParameterFilter/ShaOutParameterFilter;
```

**Comment by timinho** [comment]
Brilliant, I need more sleep :)
