### ISSUE TITLE
OwnerAddress length should be 50 and not 35

### ISSUE THREAD

**Issue by flocondetoile** [marlon-be/marlon-ogone#87]
According to https://payment-services.ingenico.com/int/en/ogone/support/guides/integration%20guides/directlink, the max length authorized for OwnerAddress parameter should be 50 characters, and not 35, as set in the AbstractPaymentRequest.php line 192.

public function setOwnerAddress($owneraddress)
    {
        if (strlen($owneraddress) > 35) {
            throw new InvalidArgumentException("Owner address is too long");
        }
        $this->parameters['owneraddress'] = $owneraddress;
    }

Not ?

**Comment by L00Cyph3r** [comment]
Any chance that the pull-request can be looked at? Seems like a small tweak.
